# Dependencies
gems:                [jekyll-paginate]
markdown:            kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title.html

# Setup
title:               "Wang Ding's Blog"
tagline:             'Haste makes waste.'
description:         '如果你看到了云雾笼罩的城堡，那么请一定走向那里去实现你非凡的梦想吧'
url:                 http://fpghwd.github.io
baseurl:             /
paginate:            10

out_url:             http://www.zmonster.me

# About/contact
author:
  name:              Wang Ding
  url:               https://github.com/fpghwd
  email:             ggwdwhu@gmail.com

# Social Media
github:              https://github.com/fpghwd

# sidebar nav
nav:
  - text: 分类
    url : /categories.html
  - text: 标签
    url : /tags.html
  - text: 归档
    url : /archive.html
  - text: 链接
    url : /link.html
  - text: 关于
    url : /about.html
  - text: Feed
    url : /feed.html

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme_settings:
  creator:           Rizky Ariestiyansyah
  codename:          Naringu
  link:              https://github.com/ariestiyansyah/naringu
